version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.44.0
    container_name: jaeger
    networks:
      - dev-network
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5775:5775/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

networks:
  dev-network:
    driver: bridge